version: '3.8'
services:
  web:
    build: .
    command: bash -c "cd ./agora && gunicorn --workers=4 --bind=0.0.0.0:8000 agora.wsgi:application"
    ports:
      - 8100:8000
    restart: always
    env_file:
      - ./.prod.env
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    env_file:
      - ./.prod.env
    volumes:
      - db_volume:/var/lib/postgres/

volumes:
  db_volume: