version: '3.8'
services:
  web:
    build: .
    # entrypoint: ./entrypoint.sh
    command: python ./agora/manage.py runserver 0.0.0.0:8000
    ports:
      - 8100:8000
    restart: always
    env_file:
      - ./.dev.env
    # depends_on:
    #   - db
    volumes:
      - ./agora:/usr/src/web/agora
  db:
    image: postgres
    restart: always
    env_file:
      - ./.dev.env
    volumes:
      - db_volume:/var/lib/postgres/

volumes:
  db_volume: