# Generated by Django 4.1 on 2022-08-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('product_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('props', models.TextField()),
            ],
        ),
    ]
